name: CI/CD Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🔹 Checkout du code
        uses: actions/checkout@v4

      - name: 🔹 Installer Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: 🔹 Construire les services Docker Compose
        run: |
          cd "Partie I"
          docker compose build

      - name: 🔹 Vérifier que les conteneurs démarrent correctement
        run: |
          cd "Partie I"
          docker compose up -d
          sleep 10  # Laisser le temps aux conteneurs de démarrer
          docker compose ps

      - name: 🔹 Lancer les tests (si nécessaire)
        run: |
          cd "Partie I"
          docker compose run --rm service_b pytest tests/

      - name: 🔹 Nettoyage des conteneurs après les tests
        run: |
          cd "Partie I"
          docker compose down
