name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🔹 Checkout du code
        uses: actions/checkout@v4

      - name: 🔹 Construire l’image Docker dans "Partie I"
        run: docker build ./Partie\ I --file ./Partie\ I/Dockerfile --tag my-image-name:$(date +%s)
